#!/bin/bash
# Start a tmux session with 3 panes
tmux new-session -d -s arcade

# Pane 1: Flask server WITH DEBUG MODE
tmux send-keys -t arcade "cd electron_app/backend && source ~/myenv/bin/activate && FLASK_ENV=development python3 flask_socket_server.py" C-m

# Pane 2: Controller monitor
tmux split-window -v -t arcade
tmux send-keys -t arcade "cd electron_app/backend && source ~/myenv/bin/activate && sleep 3 && python3 controller_monitor2.py" C-m

# Pane 3: Frontend
tmux split-window -h -t arcade
tmux send-keys -t arcade "cd electron_app/frontend && npm i && npm run dev" C-m

# Attach to session
tmux attach -t arcade
